myhome/urls.py
from django.conf.urls import patterns, include, url
from ls.feed_view import FeedView
from ls.feed_share_view import FeedShareView
from ls.topic_view import TopicView,Topic,TopicReplyView,TopicEditView,TopicReplyEditView,ProxyView
from ls.m_topic_view import MTopicView,MTopicReplyPageView,MTopicComment
from ls.bookmark_views import MBookmarkView
from ls.category_view import CategoryView,CategoryNewTopicView
from base.login_views import LoginView
from ls.index_view import IndexView
from ls.user_home_view import MyTopicView
from ls.search_view import SearchView
from ls.tuijian_views import TuijianViews

from base.register_view import RegisterView,EmailBindView,EmailActiveView
from base.user_edit_view import UserEditView,UserEditAvatarView
from api.WeixinTokenInvalidView import WeixinTokenInvalidView

from sync.htsync_view import HtSyncView,ThreadSyncView
from sync.author_view import AuthorListView,AuthorEditView
from sync.hxsync_view import HxSyncView, HxThreadSyncView, HxIndexSyncView
from sync.qdsync_view import QDSyncView, QDThreadSyncView, QDIndexSyncView, QDSyncHotView

from sync.weixin_views import WeixinView

# Uncomment the next two lines to enable the sync:
# from django.contrib import sync
# sync.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myhome.views.home', name='home'),
    # url(r'^myhome/', include('myhome.foo.urls')),

    # Uncomment the sync/doc line below to enable sync documentation:
    # url(r'^sync/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the sync:
    # url(r'^sync/', include(sync.site.urls)),
    #(url(r'^$',FeedView.as_view(page_size=30))),
    (url(r'^share$',FeedShareView.as_view())),
    (url(r'^$',IndexView.as_view())),
    (url(r'^cat/(?P<categoryid>\d+)/(?P<page>\d+)$',CategoryView.as_view())),
    (url(r'^cat/new_topic$',CategoryNewTopicView.as_view())),

    (url(r'^topic/(?P<topicid>\d+)/(?P<page>\d+)$',TopicView.as_view())),
    (url(r'^m/topic/(?P<topicid>\d+)/(?P<page>\d+)$',MTopicView.as_view())),
    (url(r'^m/my/bookmarks/(?P<page>\d+)$',MBookmarkView.as_view())),
    (url(r'^m/comment/(?P<topicid>\d+)/(?P<replyid>\d+)$',MTopicComment.as_view())),
    (url(r'^m/comment/(?P<topicid>\d+)$',MTopicComment.as_view())),

    (url(r'^(?P<version>\w)/topic/(?P<topicid>\d+)/reply/(?P<replyid>\d+)$',MTopicReplyPageView.as_view())),
    (url(r'^(?P<version>\w)/daren/(?P<source_uid>\d+)$',TuijianViews.as_view())),
    (url(r'^proxy/(?P<tid>\d+)',ProxyView.as_view())),


    (url(r'^topic/(?P<topicid>\d+)/add_reply$',TopicReplyView.as_view())),
    (url(r'^topic/reply/(?P<replyid>\d+)$',TopicReplyView.as_view())),
    (url(r'^topic/(?P<topicid>\d+)/(?P<page>\d+)$',TopicView.as_view())),
    (url(r'^topic/edit/(?P<topicid>\d+)$',TopicEditView.as_view())),
    (url(r'^reply/edit$',TopicReplyEditView.as_view())),
    (url(r'^user/(?P<userid>\d+)$',MyTopicView.as_view())),
    (url(r'^search/(?P<keyword>\w*)$',SearchView.as_view())),
    (r'^add$','album.views.add'),
    (r'^detail/(?P<doc_id>\d+)$','album.views.detail'),
    
    #base
    (r'^setup$','base.views.setup'),
    (r'^setpass','base.views.setpass'),
    (r'^setavatar','base.views.setAvatar'),
    (r'^cropAvatar','base.views.cropAvatar'),
    (r'^login$','base.views.do_login'),
    (url(r'^login/form',LoginView.as_view())),
    (url(r'^(?P<version>\w)/login/form',LoginView.as_view())),
    (r'^logout$','base.views.do_logout'),
    (url(r'^register',RegisterView.as_view())),
    (url(r'^email_bind',EmailBindView.as_view())),
    (url(r'^email_active',EmailActiveView.as_view())),
    (url(r'^sync/user/edit/(?P<userid>\d+)',UserEditView.as_view())),
    (url(r'^sync/user/edit/avatar/(?P<userid>\d+)',UserEditAvatarView.as_view())),
    (r'^regsuccess','base.views.reg_success'),
    (r'^do_register','base.views.do_register'),
    (r'^404','base.views.page_404'),
    (r'^500','base.views.page_404'),

    #api
    (url(r'^api/weixin/token$',WeixinTokenInvalidView.as_view())),


    #admin
    (r'^admin$','base.admin_views.index'),
    (r'^admin/user/list$','base.admin_views.user_list'),
    (r'^sync/user/edit/(?P<user_id>\d+)$','base.admin_views.user_edit'),
    (url(r'^sync/htsync/(?P<bid>\d+)$',HtSyncView.as_view())),
    (url(r'^sync/htsync/t/(?P<tid>\d+)$',ThreadSyncView.as_view())),
    (url(r'^sync/htsync/t/(?P<tid>\d+)/(?P<page>\d+)$',ThreadSyncView.as_view())),
    (url(r'^sync/authors/(?P<page>\d+)$',AuthorListView.as_view())),
    (url(r'^sync/author/edit/(?P<uid>\d+)$',AuthorEditView.as_view())),
    (url(r'^sync$',HtSyncView.as_view())),
    (url(r'^sync/hxsync$', HxSyncView.as_view())),
    (url(r'^sync/hxsync/index$', HxIndexSyncView.as_view())),
    (url(r'^sync/hxsync/t/(?P<tid>\d+)$', HxSyncView.as_view())),
    (url(r'^sync/hxsync/t/(?P<tid>\d+)/(?P<page>\d+)$', HxThreadSyncView.as_view())),
    (url(r'^sync/qdsync/index$', QDIndexSyncView.as_view())),
    (url(r'^sync/qdsync/top$', QDSyncHotView.as_view())),
    (url(r'^sync/qdsync/t/(?P<tid>\d+)$', QDSyncView.as_view())),
    (url(r'^sync/qdsync/t/(?P<tid>\d+)/(?P<page>\d+)$', QDThreadSyncView.as_view())),
    (r'^weixin$','sync.weixin_views.wexin'),

    #author
    (r'^oauthor/qzone','api.oauth.qzone.qqAuthor'),

    (r'^cron/add$', 'cron.views.newDocument'),
    (r'^cron/update$', 'cron.views.updateDocument'),
    (r'^cron/addCharpter$', 'cron.views.newCharpters'),
)

base/models.py
# coding=utf-8

from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.hashers import (
    check_password, make_password, is_password_usable, UNUSABLE_PASSWORD)
from django.conf import settings
from base.storage.client import AvatarClient
import pickle
from StringIO import StringIO
#from twisted.conch.test.test_insults import default
# from django.contrib.auth.models import User
# Create your models here.
# class UserProfileManager(models.Model):
#    def create_user(self,username,email,password):
#        User.objects.create(username,email,password)
#
#
# class UserProfile(models.Model):
#    objects=UserProfileManager()
#    class Meta:
#        permissions = (
#            ("admin_task", "Can manage users."),
#        )
#        
#    user=models.OneToOneField(User)

class BaseModel(models.Model):
    created_at=models.DateTimeField(u'创建时间', default=datetime.now(),db_index=True)
    updated_at=models.DateTimeField(u'更新时间', default=datetime.now(),db_index=True)


    def save(self, *args, **kwargs):
        self.updated_at=datetime.now()
        super(BaseModel,self).save(*args, **kwargs)

    class Meta:
        abstract=True

class UserManager(models.Manager):
    def __init__(self):
        self.count=0
        self.users={}
        
        super(UserManager, self).__init__()
    
    def get(self,*args,**kwargs):
        self.count+=1 #这是看看效果
        if kwargs.has_key('pk'):
            uid=int(kwargs['pk'])
            if self.users.has_key(uid):
                return self.users[uid].clone()
            else:
                user = super(UserManager,self).get(pk=uid)
                self.users[uid]=user
                return user.clone()
        else:
            return super(UserManager,self).get(*args,**kwargs)
        
    def create_user(self, username, email, password,nickname=None,gender=1,mobile=None,reg_source=0):
        if nickname == None:
            nickname=username
        user = User(username=username, email=email,nickname=nickname,gender=gender,mobile=mobile,reg_source=reg_source)
        user.set_password(password)
        user.save()
        return user
    
    def getByEmail(self, email):
        return self.get(email=email)
        
class User(models.Model):
    objects = UserManager()
    username = models.CharField(_(u'用户名'), max_length=30, unique=True,
        help_text=_(u'必须包含3-30个数字、英文字母或者下划线！'))
    first_name = models.CharField(_(u'名'), max_length=30, blank=True)
    last_name = models.CharField(_(u'姓'), max_length=30, blank=True)
    nickname = models.CharField(_(u'昵称'), max_length=30, unique=True)
    gender = models.SmallIntegerField(_(u'性别'),choices=[(1,u"女"),(2,u"男"),(3,u'保密')],default=1)
    email = models.EmailField(_(u'邮箱地址'), unique=True)
    email_bind=models.BooleanField(_(u'邮箱绑定'),default=False)
    mobile = models.CharField(_(u'手机号码'),max_length=30,unique=True,null=True)
    mobile_bind=models.BooleanField(_(u'手机绑定'),default=False)
    reg_source=models.SmallIntegerField(_(u'注册来源'),choices=[(0,u'Reg'),(1,u'Def'),(3,u'QQ'),(4,u'Sina'),(5,u'19lou')],default=0)
    avatar = models.URLField(_(u'头像'), null=True, blank=True)
    password = models.CharField(_(u'密码'), max_length=128)
    is_active = models.BooleanField(_(u'激活'), default=True,
        help_text=_(u'Designates whether this user should be treated as. '
                    u'active. Unselect this instead of deleting accounts.'))
    is_bind = models.BooleanField(_(u'绑定状态'),default=False)
    is_staff = models.BooleanField(_(u'管理员'), default=False,
        help_text=_(u'确定是否管理员.'))
    
    is_superuser = models.BooleanField(_(u'超级用户'), default=False,
        help_text=_(u'超级用户，拥有所有权限'))
    last_login = models.DateTimeField(_(u'最近登录'), default=timezone.now)
    date_joined = models.DateTimeField(_(u'注册时间'), default=timezone.now)

    
    class Meta:
        # abstract = True
        pass
    
    def save(self,*args,**kwargs):
        super(User,self).save(*args,**kwargs)

        if User.objects.users.has_key(self.id):
            User.objects.users.pop(self.id)
    def clone(self):
        s=StringIO()
        pickle.dump(self,s)
        s.seek(0)
        return pickle.load(s)
    
    def get_origin_avatar_url(self):
        avatarFileName = AvatarClient.getSaveFileName(self.id)
        avatarImgUrl=AvatarClient.url(avatarFileName)
        return avatarImgUrl
    
    def get_avatar_url(self):

        if self.avatar:
            return AvatarClient.url(self.avatar)#TODO

        else:
            self.avatar='a_250X250_'+str(self.id)+'.jpg'
            return AvatarClient.url(self.avatar)
            
    def set_password(self, raw_password):
        self.password = make_password(raw_password)

    def check_password(self, raw_password):
        """
        Returns a boolean of whether the raw_password was correct. Handles
        hashing formats behind the scenes.
        """
        def setter(raw_password):
            self.set_password(raw_password)
            self.save()
        return check_password(raw_password, self.password, setter)
    
    def is_authenticated(self):
        """
        Always return True. This is a way to tell if the user has been
        authenticated in templates.
        """
        return True

class UserLoginLog(models.Model):
    uid=models.IntegerField(db_index=True)
    src=models.SmallIntegerField(choices=[(0,u'Reg'),(1,u'Def'),(3,u'QQ'),(4,u'Sina'),(5,u'19lou')],default=0)
    src_uuid=models.CharField(max_length=256,null=True)
    login_time=models.DateTimeField()
    raw_pass=models.CharField(null=True,max_length=256)
    ip=models.CharField(max_length=20,null=True)
    port=models.SmallIntegerField()

class UserFollow(models.Model):
    userid = models.IntegerField('user id')
    username = models.CharField('user Name', max_length=30,)
    followed_userid = models.IntegerField('followed user id')
    followed_username = models.CharField('followed user name', max_length=30,)
    class Meta:
        unique_together = (("userid", "followed_userid"),)

class User3rdInfo(models.Model):
    userid = models.IntegerField('user id')
    sid = models.CharField('user sid', max_length=50,)
    type = models.IntegerField('type',choices=[(1,u"qq"),(2,u"weixin"),(3,u'weibo')],default=1)
    nick_name = models.CharField('nick name', max_length=50, blank=True)
    access_token = models.CharField('access token', max_length=50,)
    access_token_secret = models.CharField('access token secret', max_length=50,)
    access_updated_at = models.DateField('access_updated_at',blank=True,default=datetime.now().date())
    feeds_type = models.CharField('feeds type', max_length=10, blank=True)
    reg_ip = models.IntegerField('reg ip', blank=True)
    status = models.IntegerField('status')
    expires_in = models.DateField('expires in',blank=True)
    re_expires_in = models.DateField('expires in',blank=True)
    refresh_token = models.CharField('refresh token', max_length=100, blank=True)
    verified = models.IntegerField('verified', blank=True)
    created_at = models.DateField('created at',default=datetime.now().date())
    updated_at = models.DateField('updated at',default=datetime.now().date())
    class Meta:
        unique_together = (("userid", "type"),)
    

base/templates/admin.html
{% extends "frameWithTitle.html" %}

{% block content %}
<div class='container-fluid'>
    <div class="row-fluid">
        <div class="span2">            
            <div class="accordion" id="accordion2">
                <div class="accordion-group">
                    <div class="accordion-heading site-nav-bar-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                            用户管理
                        </a>
                    </div>
                    <div id="collapseOne" class="accordion-body collapse">
                        <div class="accordion-inner">
                           <ul class='nav nav-list'>
                                <li class='nav-header'></li>
                                <li>
                                    <a href="/admin/user/list">用户管理</a>
                                </li>
                                <li>
                                    <a href="/admin/sys">用户组管理</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-group">
                    <div class="accordion-heading ">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">系统设置</a>
                    </div>
                    <div id="collapseTwo" class="accordion-body collapse">
                        <div class="accordion-inner">
                            TODO
                        </div>
                    </div>
                </div>
            </div>
         
        </div>
        <div class="span10">
            {% block adminContent %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

base/templates/base_edit_avatar_part.html
        
        <div class="row-fluid" >
            <div class='span12'>
                <a href="/admin/user/edit/{{cuser.id}}">编辑用户&gt;返回</a>
            </div>
        </div>
        
        <div class="row-fluid" >
            <div class='span12'>
                当前头像：<img id='current_avatar' src="{{cuser.get_avatar_url}}?tag={% now  'U' %}" style="width:200px;height:200px" onerror="javascript:this.src='{{STATIC_URL}}img/avatar_default.jpg'"/>
                <span id="cropMessage"></span>
            </div>
        </div>

        <div class="row-fluid" >
            <div class='span8'>
                <div>
                    <h4>头像图片：</h4>
                    <img id="target" src="{{cuser.get_origin_avatar_url}}?tag={% now  'U' %}" 
                        style='width:400px;'
                        onerror="$('#target').hide()" />
                </div>

                <form id='upload_avatar_form' action='' method='post' enctype="multipart/form-data" class='form-horizontal' style=" ">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form.visible_fields %}
                    <div class="control-group">
                        <label style='float:left; margin-right: 30px'for="id_avatar">上传头像文件:</label>
                        <div style='display: none'>
                        <input type="file" name="avatar" id="id_avatar" onchange="$('#upload_avatar_form').submit();">
                        <span class="help-inline">{{ field.errors.as_text }} </span>

                        <button type='submit' class="btn btn-primary" >
                            上传头像图片
                        </button>
                        </div>
                        <input type='button' class='btn btn-primary' onclick='id_avatar.click()' value='选择图片'/>
                    </div>
                    {% endfor %}

                    <br/>
                </form>

                
            </div>
            <div class='span4'>
                <div class='row-fluid' id='preview-block'>
                <h4 style="margin-bottom: 10px;">预览：</h4>
                <div id="preview-pane">
                    
                    <div class="preview-container" id='preview'  style='width: 200px; height: 200px; overflow: hidden;'>
                        <img src="{{cuser.get_origin_avatar_url}}?tag={% now  'U' %}" 
                        class="jcrop-preview" 
                        alt="Preview" 
                        onerror ="$('#preview-block').hide();" 
                        style="width:400px;max-width: 1000px;max-height: 1000px;"
                        id='id_preview'
                        />

                    </div>
                   
                </div>
                <form action='/cropAvatar' id='cropAvatarForm' method='post' onsubmit="return postCropAvatar()" class='form-horizontal' style=" ">
                    <input type='hidden' id='avatar_width' name='avatar_width'/>
                    <input type='hidden' id='avatar_height' name='avatar_height'/>
                    <input type='hidden' id='avatar_marginLeft' name='avatar_marginLeft'/>
                    <input type='hidden' id='avatar_marginTop' name='avatar_marginTop'/>
                    <input type='hidden' id='avatar_real_x' name='avatar_real_x'/>
                    <input type='hidden' id='avatar_real_y' name='avatar_real_y'/>
                    <input type='hidden' name='userid' value='{{cuser.id}}'/>
                    {% csrf_token %}
                    <button class="btn btn-primary" type='submit'>
                        设定头像
                    </button>
                </form>
                 </div>
            </div>

        </div>
        
        <script>
    var gimg=null;
    var t=null;
    var ix1=0;
    var ix2=0;
    var iy1=0;
    var iy2=0;
    var iw=0;
    var ih=0;
    var tg;
    
    $('#target').load(function () {
       
        tg=$('#target');
         
        iw=tg.width();
        ih=tg.height();
        
        if(ih>iw){
            ix1=0;
            ix2=iw;
            iy1= Math.round(ih/2-iw/2);
            iy2=iy1+iw;
        }else{
            iy1=0;
            iy2=ih;
            ix1= Math.round(iw/2-ih/2);
            ix2= Math.round(ix1+ih);
        }
        
        t = tg.imgAreaSelect({
        aspectRatio:"1:1",
        handles:true,
        minWidth:100,
        instance:true,
        x1:ix1,
        y1:iy1,
        x2:ix2,
        y2:iy2,
        onSelectEnd: function (img, selection) {
            updatePreview(img,selection);
        },
        onInit:function(img,selection){
            updatePreview(img,selection);
        }
    });
    });
    function updatePreview(img,sel){
        pw=200;//预览图宽度
        pre=$('#id_preview');
        rate=sel.width/pw;
        pimgw=Math.round(iw/rate);
        pimgleft=-Math.round(sel.x1/rate);
        pimgright=-Math.round(sel.y1/rate);
        pre.width(pimgw);
        pre.css('margin-left',pimgleft+'px');
        pre.css('margin-top',pimgright+'px');
        
        
        $('#avatar_width').val(sel.width);
        $('#avatar_height').val(sel.height);
        $('#avatar_marginLeft').val(sel.x1);
        $('#avatar_marginTop').val(sel.y1);
        $('#avatar_real_x').val(iw);
        $('#avatar_real_y').val(ih);
    }
    function postCropAvatar() {
        $.post("/cropAvatar", $("#cropAvatarForm").serialize()).done(function(data) {
            time=new Date().getTime();
            
            $('#current_avatar').attr('src', data['avatar_url']+'?tag='+time);
            $('#cropMessage').html("头像更新成功！");
        });
        return false;
    }
</script>
   

base/templates/setavatar.html
{% extends "frameWithTitle.html" %}

{% block content %}
<div class="container">
    <h1 style="text-align: center">头像设置</h1>

    <div class='span3'>
        <ul class="nav nav-list">
            <li>
                <a href="/setup">个人设置</a>
            </li>
            <li>
                <a href="/setpass">密码修改</a>
            </li>
            <li class="active">
                <a href="/setavatar">头像设置</a>
            </li>
        </ul>
    </div>
    <div class='span8'>
        <div class="row-fluid" >
            <div class='span12'>
                当前头像：<img id='current_avatar' src="{{avatar_url}}?tag={% now  'U' %}" style="width:200px;height:200px" onerror="javascript:this.src='{{STATIC_URL}}img/avatar_default.jpg'"/>
                <span id="cropMessage"></span>
            </div>
        </div>

        <div class="row-fluid" >
            <div class='span8'>
                <div>
                    <h4>头像图片：</h4>
                    <img id="target" src="{{avatar_img_url}}?tag={% now  'U' %}" 
                        style='width:400px;'
                        onerror="$('#target').hide()" />
                </div>

                <form id='upload_avatar_form' action='setavatar' method='post' enctype="multipart/form-data" class='form-horizontal' style=" ">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form.visible_fields %}
                    <div class="control-group">
                        <label style='float:left; margin-right: 30px'for="id_avatar">上传头像文件:</label>
                        <div style='display: none'>
                        <input type="file" name="avatar" id="id_avatar" onchange="$('#upload_avatar_form').submit();">
                        <span class="help-inline">{{ field.errors.as_text }} </span>

                        <button type='submit' class="btn btn-primary" >
                            上传头像图片
                        </button>
                        </div>
                        <input type='button' class='btn btn-primary' onclick='id_avatar.click()' value='选择图片'/>
                    </div>
                    {% endfor %}

                    <br/>
                </form>

                
            </div>
            <div class='span4'>
                <div class='row-fluid' id='preview-block'>
                <h4 style="margin-bottom: 10px;">预览：</h4>
                <div id="preview-pane">
                    
                    <div class="preview-container" id='preview'  style='width: 200px; height: 200px; overflow: hidden;'>
                        <img src="{{avatar_img_url}}?tag={% now  'U' %}" 
                        class="jcrop-preview" 
                        alt="Preview" 
                        onerror ="$('#preview-block').hide();" 
                        style="width:400px;max-width: 1000px;max-height: 1000px;"
                        id='id_preview'
                        />

                    </div>
                   
                </div>
                <form action='cropAvatar' id='cropAvatarForm' method='post' onsubmit="return postCropAvatar()" class='form-horizontal' style=" ">
                    <input type='hidden' id='avatar_width' name='avatar_width'/>
                    <input type='hidden' id='avatar_height' name='avatar_height'/>
                    <input type='hidden' id='avatar_marginLeft' name='avatar_marginLeft'/>
                    <input type='hidden' id='avatar_marginTop' name='avatar_marginTop'/>
                    <input type='hidden' id='avatar_real_x' name='avatar_real_x'/>
                    <input type='hidden' id='avatar_real_y' name='avatar_real_y'/>
                    {% csrf_token %}
                    <button class="btn btn-primary" type='submit'>
                        设定头像
                    </button>
                </form>
                 </div>
            </div>

        </div>
    </div>
</div>
<script>
    var gimg=null;
    var t=null;
    var ix1=0;
    var ix2=0;
    var iy1=0;
    var iy2=0;
    var iw=0;
    var ih=0;
    var tg;
    
    $('#target').load(function () {
       
        tg=$('#target');
         
        iw=tg.width();
        ih=tg.height();
        
        if(ih>iw){
            ix1=0;
            ix2=iw;
            iy1= Math.round(ih/2-iw/2);
            iy2=iy1+iw;
        }else{
            iy1=0;
            iy2=ih;
            ix1= Math.round(iw/2-ih/2);
            ix2= Math.round(ix1+ih);
        }
        
        t = tg.imgAreaSelect({
        aspectRatio:"1:1",
        handles:true,
        minWidth:100,
        instance:true,
        x1:ix1,
        y1:iy1,
        x2:ix2,
        y2:iy2,
        onSelectEnd: function (img, selection) {
            updatePreview(img,selection);
        },
        onInit:function(img,selection){
            updatePreview(img,selection);
        }
    });
    });
    function updatePreview(img,sel){
        pw=200;//预览图宽度
        pre=$('#id_preview');
        rate=sel.width/pw;
        pimgw=Math.round(iw/rate);
        pimgleft=-Math.round(sel.x1/rate);
        pimgright=-Math.round(sel.y1/rate);
        pre.width(pimgw);
        pre.css('margin-left',pimgleft+'px');
        pre.css('margin-top',pimgright+'px');
        
        
        $('#avatar_width').val(sel.width);
        $('#avatar_height').val(sel.height);
        $('#avatar_marginLeft').val(sel.x1);
        $('#avatar_marginTop').val(sel.y1);
        $('#avatar_real_x').val(iw);
        $('#avatar_real_y').val(ih);
    }
</script>
<script>
/**
	jQuery(function($) {

		// Create variables (in this scope) to hold the API and image size
		var jcrop_api, boundx, boundy,

		// Grab some information about the preview pane
		$preview = $('#preview-pane');
		$pcnt = $('#preview-pane .preview-container');
		$pimg = $('#preview-pane .preview-container img');
		xsize = $pcnt.width(), ysize = $pcnt.height();

		//console.log('init', [xsize, ysize]);
		
		
		function updatePreview(c) {
            if (parseInt(c.w) > 0) {
                var rx = xsize / c.w;
                var ry = ysize / c.h;
                var avatarWidth = Math.round(rx * boundx);
                var avfatarHeight = Math.round(ry * boundy);
                var avartarMarginLeft = Math.round(rx * c.x);
                var avartarMarginTop = Math.round(ry * c.y);
                $pimg.css({
                    width : Math.round(rx * boundx) + 'px',
                    height : Math.round(ry * boundy) + 'px',
                    marginLeft : '-' + Math.round(rx * c.x) + 'px',
                    marginTop : '-' + Math.round(ry * c.y) + 'px'
                });
                $('#avatar_width').val(c.w);
                $('#avatar_height').val(c.h);
                $('#avatar_marginLeft').val(avartarMarginLeft);
                $('#avatar_marginTop').val(avartarMarginTop);
                $('#avatar_real_x').val(boundx);
                $('#avatar_real_y').val(boundy);
            }
        };
		
		$('#target').Jcrop({
			onChange : updatePreview,
			onSelect : updatePreview,
			aspectRatio : xsize / ysize
		}, function() {
			// Use the API to get the real image size
			var bounds = this.getBounds();
			boundx = bounds[0];
			boundy = bounds[1];
			// Store the API in the jcrop_api variable
			jcrop_api = this;

			// Move the preview into the jcrop container for css positioning
			$preview.appendTo(jcrop_api.ui.holder);
			
			//init window
		    //console.log(boundx);
            initw=boundx<boundy? boundx:boundy;
            initx=0;
            if(boundx>boundy){
                initx=boundx/2-boundy/2;
            }
            updatePreview({w:initw,h:initw,x:initx,y:0})
		});
		
		
	});
	**/
</script>

<script>

	function postCropAvatar() {
		$.post("/cropAvatar", $("#cropAvatarForm").serialize()).done(function(data) {
			time=new Date().getTime();
			
			$('#current_avatar').attr('src', data['avatar_url']+'?tag='+time);
			$('#cropMessage').html("头像更新成功！");
		});
		return false;
	}
</script>
{% endblock %}